// Java Program to Illustrate Creation Of
// Service implementation class

package com.cts.order.emailUtility.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import com.cts.order.service.OrderServiceImpl;

// Annotation
@Service
// Class
// Implementing EmailService interface
public class EmailServiceImpl implements EmailService {

	@Autowired private JavaMailSender javaMailSender;
	@Autowired
	private OrderServiceImpl orderService;

	@Value("${spring.mail.username}") private String sender;

	// Method 1
	// To send a simple email
	public String sendSimpleMail()
	{

		// Try block to check for exceptions
		try {

			// Creating a simple mail message
			SimpleMailMessage mailMessage
				= new SimpleMailMessage();

			// Setting up necessary details
			mailMessage.setFrom(sender);
			mailMessage.setTo("sinchanashettyc@gmail.com","manikantabalasubramanya47@gmail.com");
			mailMessage.setText(orderService.fetchAllPendingOrders().toString());
			//mailMessage.setText("This is an autogenerated email, Do not reply");
			mailMessage.setSubject("Test email");

			// Sending the mail
			javaMailSender.send(mailMessage);
			return "Mail Sent Successfully...";
		}

		// Catch block to handle the exceptions
		catch (Exception e) {
			return "Error while Sending Mail";
		}
	}

	// Method 2
	// To send an email with attachment
//	public String
//	sendMailWithAttachment()
//	{
//		// Creating a mime message
//		MimeMessage mimeMessage
//			= javaMailSender.createMimeMessage();
//		MimeMessageHelper mimeMessageHelper;
//
//		try {
//
//			// Setting multipart as true for attachments to
//			// be send
//			mimeMessageHelper
//				= new MimeMessageHelper(mimeMessage, true);
//			mimeMessageHelper.setFrom(sender);
//			mimeMessageHelper.setTo(details.getRecipient());
//			mimeMessageHelper.setText(details.getMsgBody());
//			mimeMessageHelper.setSubject(
//				details.getSubject());
//
//			// Adding the attachment
//			FileSystemResource file
//				= new FileSystemResource(
//					new File(details.getAttachment()));
//
//			mimeMessageHelper.addAttachment(
//				file.getFilename(), file);
//
//			// Sending the mail
//			javaMailSender.send(mimeMessage);
//			return "Mail sent Successfully";
//		}
//
//		// Catch block to handle MessagingException
//		catch (MessagingException e) {
//
//			// Display message when exception occurred
//			return "Error while sending mail!!!";
//		}
//	}
}
